(cl:defpackage ramp_planner_new-msg
  (:use )
  (:export
   "<COEFFICIENT>"
   "COEFFICIENT"
   "<CUBICREPRESENTATION>"
   "CUBICREPRESENTATION"
   "<TRAJECTORYREPRESENTATION>"
   "TRAJECTORYREPRESENTATION"
   "<TRAJECTORYREQUEST>"
   "TRAJECTORYREQUEST"
  ))

