(cl:defpackage ramp_planner_new-msg
  (:use )
  (:export
   "<BEZIFYREQUEST>"
   "BEZIFYREQUEST"
   "<COEFFICIENT>"
   "COEFFICIENT"
   "<PATHPOINTS>"
   "PATHPOINTS"
   "<TRAJECTORYREPRESENTATION>"
   "TRAJECTORYREPRESENTATION"
   "<TRAJECTORYREQUEST>"
   "TRAJECTORYREQUEST"
   "<TRAJECTORYSWAP>"
   "TRAJECTORYSWAP"
  ))

