id: 0


# Turtlebot radius ~ 0.2
# Cooky radius ~ 0.6
radius: 0.2

# Setting the Ranges in the planner code will consider the radius 
# DOF must consider robot base dimensions if the environment is surrounded by walls
# Cooky demo hallway is [10, 2.5]
DOF_min: [0,    0,  -3.14159]
DOF_max: [3.5,  3.5,  3.14159]

# Units are m/s
max_speed_linear: 0.33
max_speed_angular: 1.5708
max_acceleration: 0.33

path1start: [0.0, 0.0, 0.0]
path1waypoint1: [1.0, 1.0, 0.0]
path1waypoint2:  [0.5, 2.0, 0.0]
path1goal: [2.0, 3.0, 0.0]

path2start: [1.75, 0.0, 0.0]
path2waypoint1: [1.75, 0.0, 0.0]
path2waypoint2: [2.5, 1.5, 0.0]
path2goal: [2.5, 3.5, 0.0]

path3start: [2.0, 1.0, 0.0]
path3waypoint1: [2.0, 1.0, 0.0]
path3waypoint2: [1.0, 2.5, 0.0]
path3goal: [2.5, 3.5, 0.0]

path4start: [0.0, 0.0, 0.0]
path4goal: [2.0, 3.0, 0.0]
