// Generated by gencpp from file ramp_msgs/KnotPoint.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_KNOTPOINT_H
#define RAMP_MSGS_MESSAGE_KNOTPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ramp_msgs/MotionState.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct KnotPoint_
{
  typedef KnotPoint_<ContainerAllocator> Type;

  KnotPoint_()
    : motionState()
    , stopTime(0)  {
    }
  KnotPoint_(const ContainerAllocator& _alloc)
    : motionState(_alloc)
    , stopTime(0)  {
  (void)_alloc;
    }



   typedef  ::ramp_msgs::MotionState_<ContainerAllocator>  _motionState_type;
  _motionState_type motionState;

   typedef uint32_t _stopTime_type;
  _stopTime_type stopTime;





  typedef boost::shared_ptr< ::ramp_msgs::KnotPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::KnotPoint_<ContainerAllocator> const> ConstPtr;

}; // struct KnotPoint_

typedef ::ramp_msgs::KnotPoint_<std::allocator<void> > KnotPoint;

typedef boost::shared_ptr< ::ramp_msgs::KnotPoint > KnotPointPtr;
typedef boost::shared_ptr< ::ramp_msgs::KnotPoint const> KnotPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::KnotPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::KnotPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ramp_msgs::KnotPoint_<ContainerAllocator1> & lhs, const ::ramp_msgs::KnotPoint_<ContainerAllocator2> & rhs)
{
  return lhs.motionState == rhs.motionState &&
    lhs.stopTime == rhs.stopTime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ramp_msgs::KnotPoint_<ContainerAllocator1> & lhs, const ::ramp_msgs::KnotPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::KnotPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::KnotPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::KnotPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003814a67ae1dae25c6ac938e801efe5";
  }

  static const char* value(const ::ramp_msgs::KnotPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003814a67ae1dae2ULL;
  static const uint64_t static_value2 = 0x5c6ac938e801efe5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/KnotPoint";
  }

  static const char* value(const ::ramp_msgs::KnotPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/MotionState motionState\n"
"uint32 stopTime\n"
"\n"
"================================================================================\n"
"MSG: ramp_msgs/MotionState\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] jerks\n"
"\n"
"# change to duration\n"
"float64 time\n"
;
  }

  static const char* value(const ::ramp_msgs::KnotPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motionState);
      stream.next(m.stopTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KnotPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::KnotPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::KnotPoint_<ContainerAllocator>& v)
  {
    s << indent << "motionState: ";
    s << std::endl;
    Printer< ::ramp_msgs::MotionState_<ContainerAllocator> >::stream(s, indent + "  ", v.motionState);
    s << indent << "stopTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stopTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_KNOTPOINT_H
