// Generated by gencpp from file ramp_msgs/Path.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_PATH_H
#define RAMP_MSGS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ramp_msgs/KnotPoint.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : points()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ramp_msgs::KnotPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ramp_msgs::KnotPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::ramp_msgs::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::ramp_msgs::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::ramp_msgs::Path > PathPtr;
typedef boost::shared_ptr< ::ramp_msgs::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ramp_msgs::Path_<ContainerAllocator1> & lhs, const ::ramp_msgs::Path_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ramp_msgs::Path_<ContainerAllocator1> & lhs, const ::ramp_msgs::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc3e2e8ac00d3e652ac961c6ad8ca08d";
  }

  static const char* value(const ::ramp_msgs::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc3e2e8ac00d3e65ULL;
  static const uint64_t static_value2 = 0x2ac961c6ad8ca08dULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/Path";
  }

  static const char* value(const ::ramp_msgs::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/KnotPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: ramp_msgs/KnotPoint\n"
"ramp_msgs/MotionState motionState\n"
"uint32 stopTime\n"
"\n"
"================================================================================\n"
"MSG: ramp_msgs/MotionState\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] jerks\n"
"\n"
"# change to duration\n"
"float64 time\n"
;
  }

  static const char* value(const ::ramp_msgs::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::Path_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ramp_msgs::KnotPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_PATH_H
