// Generated by gencpp from file ramp_msgs/Circle.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_CIRCLE_H
#define RAMP_MSGS_MESSAGE_CIRCLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct Circle_
{
  typedef Circle_<ContainerAllocator> Type;

  Circle_()
    : center()
    , radius(0.0)  {
    }
  Circle_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::ramp_msgs::Circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::Circle_<ContainerAllocator> const> ConstPtr;

}; // struct Circle_

typedef ::ramp_msgs::Circle_<std::allocator<void> > Circle;

typedef boost::shared_ptr< ::ramp_msgs::Circle > CirclePtr;
typedef boost::shared_ptr< ::ramp_msgs::Circle const> CircleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::Circle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::Circle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ramp_msgs::Circle_<ContainerAllocator1> & lhs, const ::ramp_msgs::Circle_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ramp_msgs::Circle_<ContainerAllocator1> & lhs, const ::ramp_msgs::Circle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::Circle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::Circle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab296cd39c1a1fa7dd67209d6a4767e1";
  }

  static const char* value(const ::ramp_msgs::Circle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab296cd39c1a1fa7ULL;
  static const uint64_t static_value2 = 0xdd67209d6a4767e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/Circle";
  }

  static const char* value(const ::ramp_msgs::Circle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 center\n"
"float64 radius\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ramp_msgs::Circle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::Circle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Circle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::Circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::Circle_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_CIRCLE_H
